export interface Project {
    roomNo: string;
    occupants: string[];
    gender: string;
    keyHolder: string;
  }
  
  export const PROJECTS: Project[] = [
    {
      roomNo: "236",
      occupants: ["Lakshitha Wijethunga", "Uditha Ranasinghe", "Linal Hansana"],
      gender: "Male",
      keyHolder: "Lakshitha Wijethunga",
    },
    {
      roomNo: "237",
      occupants: ["Mahima Yasas", "Tharuka Gunarathne", "Dulain Jayasumana"],
      gender: "Male",
      keyHolder: "Mahima Yasas",
    },
    {
      roomNo: "238",
      occupants: ["Chelaka Wijesekara", "Dilum Kalubowila", "Yenul Perera"],
      gender: "Male",
      keyHolder: "Chelaka Wijesekara",
    },
    {
      roomNo: "239",
      occupants: ["Godfri John"],
      gender: "Male",
      keyHolder: "Godfri John",
    },
    {
      roomNo: "240",
      occupants: ["Mohamad Shaahid", "Yehan Namarathna", "Vismitha Gunasekara"],
      gender: "Male",
      keyHolder: "Mohamad Shaahid",
    },
    {
      roomNo: "241",
      occupants: ["Lahiru Dinusha", "Sudeera Jayarathna", "Vihanga Deemantha"],
      gender: "Male",
      keyHolder: "Lahiru Dinusha",
    },
    {
      roomNo: "242",
      occupants: ["Divya Dulanjali", "Pamali Amesha", "Heshani Navodya"],
      gender: "Female",
      keyHolder: "Divya Dulanjali",
    },
    {
      roomNo: "243",
      occupants: ["Sadavi Kuruwitaarachchige", "Viduni Kongahage", "Navodya Thilini"],
      gender: "Female",
      keyHolder: "Sadavi Kuruwitaarachchige",
    },
    {
      roomNo: "244",
      occupants: ["Mahendri Hemachandra", "Chamodya Bandarawatta", "Subodha Emanuwel"],
      gender: "Female",
      keyHolder: "Mahendri Hemachandra",
    },
    {
      roomNo: "245",
      occupants: ["Aamina Riffath", "Kavindhya Malshani", "Amoda Fernando"],
      gender: "Female",
      keyHolder: "Aamina Riffath",
    },
    {
      roomNo: "250",
      occupants: ["Minangi Jayasinghe", "Savithmi Minsaree", "Poojanee Weerasena"],
      gender: "Female",
      keyHolder: "Minangi Jayasinghe",
    },
    {
      roomNo: "251",
      occupants: ["Shenan Nathaniel", "Sasith Vishwa Darshana", "Vishwa Kaushalya"],
      gender: "Male",
      keyHolder: "Shenan Nathaniel",
    },
    {
      roomNo: "252",
      occupants: ["Sakila Thejana", "Bhanuka Induwara", "Amzal Foumi"],
      gender: "Male",
      keyHolder: "Sakila Thejana",
    },
    {
      roomNo: "253",
      occupants: ["Kalindu De Silva", "Mevinu Liyanage", "Dinil Hansara"],
      gender: "Male",
      keyHolder: "Kalindu De Silva",
    },
    {
      roomNo: "254",
      occupants: ["Imindu Jayasekara", "Yeshan KP", "Kavindu Prabhash"],
      gender: "Male",
      keyHolder: "Imindu Jayasekara",
    },
    {
      roomNo: "255",
      occupants: ["Ravinesh Perera", "Harith Sandundeniya", "Sabeelur Rashaad Mohamed Razeen"],
      gender: "Male",
      keyHolder: "Ravinesh Perera",
    },
    {
      roomNo: "256",
      occupants: ["Janindu Hasanka", "Rumeth Amarasiri", "Supun Jayasinghe"],
      gender: "Male",
      keyHolder: "Janindu Hasanka",
    },
    {
      roomNo: "257",
      occupants: ["Saneesha Dulhara", "Yuneth Withanachchi", "Dishan Bashitha"],
      gender: "Male",
      keyHolder: "Saneesha Dulhara",
    },
    {
      roomNo: "258",
      occupants: ["Kavindu Madushan", "Vihan Hettiarachchi", "Dileepa Bandara", "Dahamya Vinradi"],
      gender: "Male",
      keyHolder: "Kavindu Madushan",
    },
    {
      roomNo: "259",
      occupants: ["Dahamya Vinradi", "Fathima Isthikar", "Jayashni Rodrigo"],
      gender: "Female",
      keyHolder: "Dahamya Vinradi",
    },
    {
      roomNo: "260",
      occupants: ["Harithanjali Weerakkody", "Umayangana Madurawala"],
      gender: "Female",
      keyHolder: "Harithanjali Weerakkody",
    },
    {
      roomNo: "261",
      occupants: ["Venuki Wijeratne", "Nilma Malkini"],
      gender: "Female",
      keyHolder: "Venuki Wijeratne",
    },
    {
      roomNo: "262",
      occupants: ["Senaya Dharmadasa", "Kethaki Wijesooriya"],
      gender: "Female",
      keyHolder: "Senaya Dharmadasa",
    },
    {
      roomNo: "263",
      occupants: ["Dinuki Masakorala", "Lakshajini Ruparajan"],
      gender: "Female",
      keyHolder: "Dinuki Masakorala",
    },
    {
      roomNo: "264",
      occupants: ["Rashmika Guruge", "Gayani Malalgoda", "Savandi Liyanayapa"],
      gender: "Female",
      keyHolder: "Rashmika Guruge",
    },
    {
      roomNo: "265",
      occupants: ["Leeza Gilbert", "Sanumi Nimethra"],
      gender: "Female",
      keyHolder: "Leeza Gilbert",
    },
    {
      roomNo: "266",
      occupants: ["Nadali Hansani", "Samadhi Hemantha"],
      gender: "Female",
      keyHolder: "Nadali Hansani",
    },
    {
      roomNo: "267",
      occupants: ["Dineth Wijesuriya", "Rashdhan Mohomed", "Ishan Balasooriya", "Thisara Kawinda"],
      gender: "Male",
      keyHolder: "Dineth Wijesuriya",
    },
    {
      roomNo: "268",
      occupants: ["Thisara Kawinda", "Anuja Mahamalage", "Tharindu Widanagama"],
      gender: "Male",
      keyHolder: "Thisara Kawinda",
    },
    {
      roomNo: "269",
      occupants: ["Dulen Withanage", "Damith Wijemanna", "Shamli Bin Jameel", "Srimuralitharan Elilavan"],
      gender: "Male",
      keyHolder: "Dulen Withanage",
    },
    {
      roomNo: "270",
      occupants: ["Raj Waidyasekara", "Thisara Randam", "Thumal Kariyapperuma", "Bawantha Jayanath"],
      gender: "Male",
      keyHolder: "Raj Waidyasekara",
    },
    {
      roomNo: "271",
      occupants: ["Nadun Weerakkody", "Tilan Eranga", "Balamurali Pakeetharan", "Induwara Lakthila"],
      gender: "Male",
      keyHolder: "Nadun Weerakkody",
    },
    {
      roomNo: "272",
      occupants: ["Mihan Ekanayake", "Benjamin Gnanapragasam", "Methal Abeywickrama", "Sandaru Dissanayake"],
      gender: "Male",
      keyHolder: "Mihan Ekanayake",
    },
    {
      roomNo: "273",
      occupants: ["Adithya Kalhan", "Janindu Wijesinghe", "Aflal Zahreen", "Manindu Upek"],
      gender: "Male",
      keyHolder: "Adithya Kalhan",
    },
    {
      roomNo: "274",
      occupants: ["Jemima Mohamed", "Kasundi Sanara", "A.B.Shishanika Kavindya", "Subanki Subaschandran"],
      gender: "Female",
      keyHolder: "Jemima Mohamed",
    },
    {
      roomNo: "275",
      occupants: ["Christy Binni", "Uthpala Kalupathirana", "Puravi Kulathunga", "Minethma Wickramasinghe"],
      gender: "Female",
      keyHolder: "Christy Binni",
    },
    {
      roomNo: "276",
      occupants: ["Manisha Selvanayagam", "Minduli Atapattu", "Methya Weeraratne", "Devmi Galagedara"],
      gender: "Female",
      keyHolder: "Manisha Selvanayagam",
    },
    {
      roomNo: "277",
      occupants: ["Pavani Attanayake", "Sanduni Wijekoon", "Sehansa Palliyaguru", "Disandi Sandithna"],
      gender: "Female",
      keyHolder: "Pavani Attanayake",
    },
    {
      roomNo: "278",
      occupants: ["Savidya Wijayakulasooriya", "Nethmi Maduhara", "Maheesha Deraniyagala", "Pethara Ranasinghe"],
      gender: "Female",
      keyHolder: "Savidya Wijayakulasooriya",
    },
    {
      roomNo: "279",
      occupants: ["Dinithi Thilakaratne", "Tracey Johnson", "Chamie Ranawakaarachchi", "Pumuthu Weerakoon"],
      gender: "Female",
      keyHolder: "Dinithi Thilakaratne",
    },
    {
      roomNo: "280",
      occupants: ["Chamlika Wijesinghe", "Bumini Uyanahewa", "Kithmini Hettiarachchi", "Navapriyah Krishnan"],
      gender: "Female",
      keyHolder: "Chamlika Wijesinghe",
    },
    {
      roomNo: "281",
      occupants: ["Amasha Fernando", "Dinidi Senanayake", "CHITHMI NAVODYA", "Upetha Ariyarathne"],
      gender: "Female",
      keyHolder: "Amasha Fernando",
    },
    {
      roomNo: "282",
      occupants: ["Kavindya Bandara", "Sachini Rajapaksha", "Thehasa Hewavitharana", "Pumudi Peduruarachchi"],
      gender: "Female",
      keyHolder: "Kavindya Bandara",
    },
    {
      roomNo: "283",
      occupants: ["Madhunishaa Yogendran", "Shimasha Manawadu", "Sadeeshie Ravindya", "Gimhani Jayasekara"],
      gender: "Female",
      keyHolder: "Madhunishaa Yogendran",
    },
    {
      roomNo: "284",
      occupants: ["Tharuka Fernando", "Navoda Sandamini", "Kavini Wijesiriwardena", "Limantha Adikari"],
      gender: "Female",
      keyHolder: "Tharuka Fernando",
    },
    {
      roomNo: "285",
      occupants: ["H.A.Promodi maheshika", "Oshadi Liyanage", "Sayumi Ekanayake", "Duwasha Algama"],
      gender: "Female",
      keyHolder: "H.A.Promodi maheshika",
    },
    {
      roomNo: "286",
      occupants: ["Shinthurie Markandakuganathan", "Nirmani Weerakoon", "Anjalee perera", "Malithi Dharmasiri"],
      gender: "Female",
      keyHolder: "Shinthurie Markandakuganathan",
    },
    {
      roomNo: "287",
      occupants: ["Amani Jayasekara", "Hansika Bandara", "Bavisyanthe Shanmugadas"],
      gender: "Female",
      keyHolder: "Amani Jayasekara",
    },
    {
      roomNo: "288",
      occupants: ["Vihangi Ranaweera", "Zahra Bathool", "Imaya Jayarathna"],
      gender: "Female",
      keyHolder: "Vihangi Ranaweera",
    },
    {
      roomNo: "289",
      occupants: ["Thisuni Kuruwitaarachchige", "Nayanalochana Handapangoda", "Mithuni Nadeesha"],
      gender: "Female",
      keyHolder: "Thisuni Kuruwitaarachchige",
    },
    {
      roomNo: "290",
      occupants: ["Nawoda Uththarani", "Sachini Gunawardhana", "Monali Edirisinghe"],
      gender: "Female",
      keyHolder: "Nawoda Uththarani",
    },
    {
      roomNo: "291",
      occupants: ["Methara Wanigasinghe", "Shahnaas Rafi", "Gayathmee Perera"],
      gender: "Female",
      keyHolder: "Methara Wanigasinghe",
    },
    {
      roomNo: "292",
      occupants: ["Raveesha Bandara", "Dilthara de Silva", "Melanie Dassanayake"],
      gender: "Female",
      keyHolder: "Raveesha Bandara",
    },
    {
      roomNo: "293",
      occupants: ["Dinithi Pamudika", "Imandi Amalna"],
      gender: "Female",
      keyHolder: "Dinithi Pamudika",
    },
    {
      roomNo: "294",
      occupants: ["Sachinthani Ketakumbura", "Vinuli Gunaratne", "Methpani Rathnayake"],
      gender: "Female",
      keyHolder: "Sachinthani Ketakumbura",
    },
    {
      roomNo: "295",
      occupants: ["Nethuli Paranavidana", "ANUKI VIMAYA ADIKARI", "Dinadi Jayathilaka"],
      gender: "Female",
      keyHolder: "Nethuli Paranavidana",
    },
    {
      roomNo: "296",
      occupants: ["Imelsha Fernando Aththachchi", "Samindi Keel", "Samithri Miulandi Gunasekara"],
      gender: "Female",
      keyHolder: "Imelsha Fernando Aththachchi",
    },
    {
      roomNo: "297",
      occupants: ["Samadhi Wadithya", "Omali Weerasinghe", "Hashini Hapuarachchi"],
      gender: "Female",
      keyHolder: "Samadhi Wadithya",
    },
    {
      roomNo: "298",
      occupants: ["Ayshah Shaheed", "Dinuri Geeganage", "Hani Rudhthiya"],
      gender: "Female",
      keyHolder: "Ayshah Shaheed",
    },
    {
      roomNo: "299",
      occupants: ["Nethma Dewmini", "Senugi Mendis", "Shenise Pronk"],
      gender: "Female",
      keyHolder: "Nethma Dewmini",
    },
    {
      roomNo: "300",
      occupants: ["Mishara Athukorala", "Ravindu Jayasekara", "Savinda Sithum"],
      gender: "Male",
      keyHolder: "Mishara Athukorala",
    },
    {
      roomNo: "301",
      occupants: ["Desandu Wanniarachchi", "Vishal Hadharshan", "Thedapun Wanninaika"],
      gender: "Male",
      keyHolder: "Desandu Wanniarachchi",
    },
    {
      roomNo: "302",
      occupants: ["Nikila Silva", "Mathumithan Arulanantham", "Vabeeshan Vasantharajan"],
      gender: "Male",
      keyHolder: "Nikila Silva",
    },
    {
      roomNo: "303",
      occupants: ["Yohan Wickramasinghe", "Hiran Samahon", "Ryan Fonseka"],
      gender: "Male",
      keyHolder: "Yohan Wickramasinghe",
    },
    {
      roomNo: "304",
      occupants: ["Oshan Indusara", "Gayan Kanchana", "Chamin Jayasoma"],
      gender: "Male",
      keyHolder: "Oshan Indusara",
    },
    {
      roomNo: "305",
      occupants: ["Deveen Chandira", "Nirmal Dilip", "Kokulan Kugathasan"],
      gender: "Male",
      keyHolder: "Deveen Chandira",
    },
    {
      roomNo: "306",
      occupants: ["Dinuka Wimalagunasekara", "Ashfaaq Ashrak", "Thisuka De Silva"],
      gender: "Male",
      keyHolder: "Dinuka Wimalagunasekara",
    },
  ];